pcdet:
  ros__parameters:
    config_file: "cfgs/custom_models/TED-S-MATERIAL-CART.yaml"
    model_file: "checkpoints/TED-S-MATERIAL-CART.pth"
    allow_memory_fractioning: False
    allow_score_thresholding: True
    num_features: 4
    device_id: 0
    device_memory_fraction: 6.0
    threshold_array: [0.8, 0.8, 0.8] # [Car, Pedestrian, Bicycle]